// Code generated by Kitex v0.9.1. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	video "tiktok/kitex_gen/video"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, req *video.FeedReq, callOptions ...callopt.Option) (r *video.FeedResp, err error)
	Publish(ctx context.Context, req *video.PublishReq, callOptions ...callopt.Option) (r *video.PublishResp, err error)
	List(ctx context.Context, req *video.ListReq, callOptions ...callopt.Option) (r *video.ListResp, err error)
	Popular(ctx context.Context, req *video.PopularReq, callOptions ...callopt.Option) (r *video.PopularResp, err error)
	Search(ctx context.Context, req *video.SearchReq, callOptions ...callopt.Option) (r *video.SearchResp, err error)
	Info(ctx context.Context, req *video.InfoReq, callOptions ...callopt.Option) (r *video.InfoResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) Feed(ctx context.Context, req *video.FeedReq, callOptions ...callopt.Option) (r *video.FeedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, req)
}

func (p *kVideoServiceClient) Publish(ctx context.Context, req *video.PublishReq, callOptions ...callopt.Option) (r *video.PublishResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Publish(ctx, req)
}

func (p *kVideoServiceClient) List(ctx context.Context, req *video.ListReq, callOptions ...callopt.Option) (r *video.ListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.List(ctx, req)
}

func (p *kVideoServiceClient) Popular(ctx context.Context, req *video.PopularReq, callOptions ...callopt.Option) (r *video.PopularResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Popular(ctx, req)
}

func (p *kVideoServiceClient) Search(ctx context.Context, req *video.SearchReq, callOptions ...callopt.Option) (r *video.SearchResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Search(ctx, req)
}

func (p *kVideoServiceClient) Info(ctx context.Context, req *video.InfoReq, callOptions ...callopt.Option) (r *video.InfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Info(ctx, req)
}
