linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused
    - asciicheck
    - bodyclose
    - exhaustive


linters-settings:
  errcheck:
    check-type-assertions: true

  govet:
    disable-all: true
    enable:
      - appends
      - bools
      - defers
      - httpresponse
      - shadow
      - unmarshal
      - unreachable
      - printf
      - nilfunc
      - nilness
      - shift