apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaeger-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jaeger-storage
  hostPath:
    path: /data/jaeger
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jaeger-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc
spec:
  storageClassName: jaeger-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jaeger
spec:
  replicas: 1
  serviceName: jaeger
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6831
        volumeMounts:
        - name: jaeger-pv
          mountPath: /data
      volumes:
      - name: jaeger-pv
        persistentVolumeClaim:
          claimName: jaeger-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - protocol: TCP
    port: 6831
    targetPort: 6831
    nodePort: 30006
  type: NodePort
