apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prom-storage
  hostPath:
    path: /data/prom
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prom-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
spec:
  storageClassName: prom-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prom
spec:
  replicas: 1
  serviceName: prom
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
      - name: prom
        image: prom/prometheus:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prom-pv
          mountPath: /data
      volumes:
      - name: prom-pv
        persistentVolumeClaim:
          claimName: prom-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prom
spec:
  selector:
    app: prom
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30004
  type: NodePort
