// Code generated by hertz generator.

package main

import (
	handler "tiktok/cmd/api/biz/handler"
	"tiktok/cmd/api/biz/ws"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	r.GET("/ws", ws.HandleConnections)
	// your code ...

}
