apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: apitiktok:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 10001
        - containerPort: 19091
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:

  type: NodePort
  ports:
  - name: http
    port: 10001
    targetPort: 10001
    nodePort: 30020
  - name: hertz
    port: 19091
    targetPort: 19091
    nodePort: 30021
  selector:
    app: api-service
