apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
      - name: video-service
        image: videotiktok:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8882
        - containerPort: 6061
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  ports:
  - name: http
    port: 8882
    targetPort: 8882
  - name: pprof
    port: 6061
    targetPort: 6061


  selector:
    app: video-service
