SqlUserName: "root"
SqlPassword: "123456"
DataBase: "videoWebsite"
MysqlIP: 127.0.0.1
#"192.168.102.126"
RabbitmqUserName: "guest"
RabbitmqPassword: "guest"
RabbitmqIP : "127.0.0.1"
#RabbitmqIP: "192.168.239.126:5672"
ExchangeName: "direct"

RedisAddr: "127.0.0.1:6379"
RedisPassword: 
RedisDB: 0


EndPoint        : "localhost:9000"
AccessKeyID     : "minioadmin"
SecretAccessKey : "minioadmin"
SSL             : false
BucketName      : "videoweb"

etcd:
  addr: "localhost:2379"

jaeger:
  addr: "localhost:6831"

  


