// Code generated by Kitex v0.9.1. DO NOT EDIT.

package pictureservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	picture "tiktok/kitex_gen/picture"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Insert(ctx context.Context, req *picture.InsertRequest, callOptions ...callopt.Option) (r *picture.InsertResponse, err error)
	SearchByImage(ctx context.Context, req *picture.SearchByImageRequest, callOptions ...callopt.Option) (r *picture.SearchResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPictureServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPictureServiceClient struct {
	*kClient
}

func (p *kPictureServiceClient) Insert(ctx context.Context, req *picture.InsertRequest, callOptions ...callopt.Option) (r *picture.InsertResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Insert(ctx, req)
}

func (p *kPictureServiceClient) SearchByImage(ctx context.Context, req *picture.SearchByImageRequest, callOptions ...callopt.Option) (r *picture.SearchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchByImage(ctx, req)
}
